### PR TITLE
Pathway progress

### LINKED ISSUE #260: Pathway progess indicator
We should have a checklist indicator for you to mark as an indicator of you earning/completing a skill. Can elaborate on this more wt @zzzndr / pull some quick designs.

### PR DESCRIPTION
**Pull request by stenington**
I think this will close #260 and maybe #258. Pathway requirements marked as earned will mark the underlying badge as earned, thereby providing dummy data for that category in a sense.

### CODE REVIEW

**Comment by stenington** [comment]
http://discovery-260.herokuapp.com/

**Comment by stenington** [comment]
I know there are a few problems, so I've pushed the WIP PR to http://discovery-260.herokuapp.com/ for a round of preliminary QA to figure out what further tweaks to make.

**Comment by chloeatplay** [comment]
This looks cool! I just went through the main actions and it works well for me. A few issues I see from an experience point of view. Once you have checked all of these you should get some indication that you completed the pathway ==> @zzzndr had some screens on that I believe. The other question I have is - do the checked ones appear in your earned section too? I think they should, since this is all self-assessed. @zzzndr can you also do some QA in case I missed anything?

**Comment by stenington** [comment]
@chloeatplay If you check a bunch of badges and then go to the add screen, you **won't** see the earned badges there until you refresh the page, which is a bug. But if you check some badges and then go to your dashboard, for example, they will show up.

The indication of completing a pathway should be a separate ticket, I think, to prevent this from getting too huge.

**Comment by chloeatplay** [comment]
k, agreed- will try to recreate that bug & open a new ticket

**Comment by stenington** [comment]
I think I'll merge this in and fix the earned section updating separately. It seems to be a general problem on the dashboard page with favoriting too.

**Pull request merged**
