### PR TITLE
Pathwayz lander UI

### PR DESCRIPTION
**Pull request by ZeeJab**
Adds initial styling for pathway lander desktop version

### CODE REVIEW

**Comment by ZeeJab** [comment]
@stenington if you'd like review this and merge it in. I have to change the image for mobile version but besides that it's good to go as far as the lander for now...

**Comment by stenington** [comment]
Looks like the background stops resizing as you shrink the desktop window down, which shifts the image out of the circle:

screen shot 2014-04-03 at 4 26 59 pm

**Comment by stenington** [comment]
The changes are also interacting with how the pathway editor is sized somehow, scaling it way down at narrow window widths and on mobile:

screen shot 2014-04-03 at 4 29 53 pm

**Comment by ZeeJab** [comment]
ok awesome. will fix. thanks @stenington :-)!

**Comment by stenington** [comment]
@chloeatplay @zzzndr BTW I'm going to try out a heroku-instance-per-PR now that there are multiple contributors, I think. Here's @ZeeJab's initial changes with more on the way: http://discovery-175.herokuapp.com/

**Comment by chloeatplay** [comment]
:thumbsup:

**Comment by ZeeJab** [comment]
@stenington I sent you an email, I've made the fixes but I can't commit them for some reason. Ping me when you get a chance :-)

**Comment by ZeeJab** [comment]
@stenington i finally pushed it. this fixes the issues you had mentioned. it should be good to be merged in now.

**Comment by ZeeJab** [comment]
@stenington I've also rebased it with master and resolved merge conflicts.

**Comment by stenington** [comment]
@ZeeJab Awesome, thanks! Updated http://discovery-175.herokuapp.com/

**Comment by stenington** [comment]
Ok, @tomtang539 and @mchizek will incorporate this into a PR in progress, so closing this one out.

**Comment by shiba4life** [comment]
@zeejab great work, I'm using a lot of your techniques here.  Quick question, how did you get the editor to change from 5 columns to 3 columns on resizing?  I'm trying to figure it out from your code but figured I'd ask.  @stenington let me know if have any thoughts on how to do this.

**Pull request closed without merging**
