### PR TITLE
Issue190

### PR DESCRIPTION
**Pull request by malynda**
Changes to many of the UI issues!

### CODE REVIEW

**Comment by malynda** [comment]
includes #186, #191, #200, #201, #169,

**Comment by ZeeJab** [comment]
@mchizek && @tomtang539 can you rebase this with master and resolve conflicts please?

**Comment by stenington** [comment]
http://discovery-211.herokuapp.com/ is up.

**Comment by stenington** [comment]
Woah! Something has gone awry here.

I have a copy of this branch from this morning that I can open a PR against and we can work from there.

**Comment by shiba4life** [comment]
I've been trying to rebase Mozilla's master branch with ours and got a ton of merge conflicts.  I think they're all resolved now but I'm probably doing is wrong.

**Comment by stenington** [comment]
We have one with a cleaner history in #213, so closing here.

**Pull request closed without merging**
