### PR TITLE
Fixes for stuff

### LINKED ISSUE #395: Featured tag gets cloned
Using tags for featured pathways isn't as clever as we thought. Tags get copied over when someone clones a pathway, so all pathways end up with that tag.

### PR DESCRIPTION
**Pull request by stenington**
Fixes #395 and a few other bugs. I KEEP FINDING BUGS.

:bug:

### CODE REVIEW

**Comment by jpcamara** [comment]
I'm pretty sure software is like the movie Speed. But instead of having to keep a bus above 50mph, you have to keep creating and finding bugs. Otherwise you explode :fireworks:

**Comment by stenington** [comment]
Added a fix for the final comment in #297

**Comment by stenington** [comment]
@jpcamara THAT'S NOT EVEN FUNNY that's like my worst nightmare

**Comment by stenington** [comment]
Aaaaaand #326

**Comment by jpcamara** [comment]
Kreuger

**Pull request merged**
