### PR TITLE
Add notes to pathways

### PR DESCRIPTION
**Pull request by stenington**
There's some pretty egregious code in here, but I think it works.

### CODE REVIEW

**Comment by chloeatplay** [comment]
:notebook: :point_right: :tada:

**Comment by stenington** [comment]
http://discovery-345.herokuapp.com/

**Comment by chloeatplay** [comment]
OMG I just made a note!!! cc @zzzndr :dancer:

**Comment by zzzndr** [comment]
This is too cool that we will have notes after all! \o/
Works like a charm here in firefox, safari & chrome ((:

If there is time to implement it, I can quickly create a variation of the badge header without the white circular badge background

**Comment by zzzndr** [comment]
If possible it would be great if the storybit icon can be 100px wide in the header to make the header more balanced (:

here is a sample of a header with the storybit icon which is 100px wide
https://redpen.io/vdeb7471064e7748e4

here is the link to the storybit header

desktop
https://www.dropbox.com/s/r3mahu9wdbsq3wo/storybitHeaderDesktop2000.svg

mobile
https://www.dropbox.com/s/hmkmiad9sgiin01/storybitsHeaderMobile.svg

**Comment by stenington** [comment]
@zzzndr can you provide a storybit icon without all the whitespace around it?
screen shot 2014-05-21 at 9 18 52 am

**Comment by zzzndr** [comment]
voila:
https://www.dropbox.com/s/7tk93zghhhkygkd/storybitIcon.svg

**Comment by stenington** [comment]
In the spreadsheet, on a pathway page add `Note title` and `Note body` columns and fill in values there along with an `x` and a `y` to preload pathways with notes.

See "Squiggly pathway" sheet for an example.

**Comment by chloeatplay** [comment]
:thumbsup: cc @LucasBlair

**Pull request merged**
