### PR TITLE
Add missing header-dropdown class

### PR DESCRIPTION
**Pull request by stenington**

### CODE REVIEW

**Comment by threeqube** [comment]
Did you sleep last night???

**Comment by stenington** [comment]
NOT MUCH. 

(6am - 8am appointment window for A/C repair.)

**Comment by threeqube** [comment]
Yeah man! Get some :zzz:s!

**Comment by zzzndr** [comment]
when i saw the mails arriving from Mike i actually checked East Coast time ((:

**Comment by chloeatplay** [comment]
Mandatory owl badge ==>
animalz-high rez-06

**Pull request merged**
