### PR TITLE
Add responsive prototype ribbon

### PR DESCRIPTION
**Pull request by stenington**
For #342

### CODE REVIEW

**Comment by stenington** [comment]
screen shot 2014-05-22 at 11 42 21 am
screen shot 2014-05-22 at 11 42 56 am

With a narrower window the ribbon would eclipse the mozilla tab, so it does this:
screen shot 2014-05-22 at 11 42 16 am

**Comment by zzzndr** [comment]
functional-fancy ((:

**Comment by stenington** [comment]
@chloeatplay @zzzndr Style suggestions welcome, if you have any :)

**Comment by zzzndr** [comment]
okido, can do some suggestions which don't take much time!

**Comment by stenington** [comment]
Could always throw a few of these in there:

**Comment by threeqube** [comment]
Ha! :construction: Me gusta.

**Comment by zzzndr** [comment]
what about this for styling?

desktop
https://redpen.io/rbbb75b64d3a993540

tablet
https://redpen.io/qu424398c71b886117

**Comment by zzzndr** [comment]
here are new versions!

desktop
https://redpen.io/zvf04fe510c5fd1173

tablet
https://redpen.io/tr2b2587c15cf4f533

**Comment by zzzndr** [comment]
here are updated versions (:

desktop
https://redpen.io/ox8abba943121d6d8e

tablet
https://redpen.io/jh92a29616786df239

**Comment by chloeatplay** [comment]
:+1:

**Comment by zzzndr** [comment]
DESKTOP:
Background color ribbon: orange, #fc9141

Open Sans Semibold
font-size: 16px
color: white
text in capitals

link to the dino:
https://www.dropbox.com/s/hpd9mu09y5eza60/iconMozilla-01.svg

About the size of the dino, please try to make it about the same height as the text (:

TABLET:
height of the horizontal banner 50px

Open Sans Semibold
font-size: 20px
color: white
text in capitals

**Comment by stenington** [comment]
screen shot 2014-05-22 at 6 44 03 pm

**Comment by chloeatplay** [comment]
Like a pro. :+1:

**Comment by zzzndr** [comment]
fancy!

**Pull request merged**
