### PR TITLE
Lose top bar for hamburger menu

### PR DESCRIPTION
**Pull request by stenington**
Now I want a hamburger.

### CODE REVIEW

**Comment by jpcamara** [comment]
Now _I_ want a hamburger.  :hamburger:

**Comment by stenington** [comment]
DUDE WHAT IF THIS APP **WAS** A HAMBURGER?!

**Comment by chloeatplay** [comment]
:hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: 
:balloon:

**Comment by jpcamara** [comment]
haha APPBURGER!

if the badge ecosystem was a hamburger - what would the components be??
bun - badge class
patty - badge assertion
value meal - pathway

**Pull request merged**
