### PR TITLE
Directory client

### PR DESCRIPTION
**Pull request by jpcamara**
This is an implementation for using the directory from the discovery project. It contains an api endpoint (/search), the directory client, and human models/views for interfacing with the server. I can change this to a WIP if you want to review and do some back and forth here. 
I tried to follow what conventions I could see in the project in terms of how views and pages were setup. Mostly mimicked your style since I am not very familiar with the intricacies of HumanView.
Also updated the readme to include settings needed to hit the directory.

### CODE REVIEW

**Comment by stenington** [comment]
Cool, looking through all of this now.

@jpcamara if you get a chance to check out the merge conflict, I'd appreciate it.

**Comment by stenington** [comment]
Woo, check it out! http://discovery-196.herokuapp.com/recent 

I see we have some work to do on our HTML/CSS when badges of different image sizes and title lengths come in. :)

**Comment by threeqube** [comment]
Whoa! Awesome! :tada:

**Comment by jpcamara** [comment]
I fixed the merge conflict and pushed it (no rebase sorry :frowning:). Should be good to go now

**Pull request closed without merging**
