### PR TITLE
Go to badge page when badge clicked in editor

### PR DESCRIPTION
**Pull request by stenington**
It's a little awkward to try to discern clicks from drags, but it basically works.

### CODE REVIEW

**Comment by chloeatplay** [comment]
@stenington hmm wondering if we should try the "i" label that @zzzndr had designed at some point.

**Comment by zzzndr** [comment]
here is the link to the wiki
https://github.com/mozilla/openbadges-discovery/wiki/Discovery-Pathway-UI-Design#d6--m6

here is the link to the graphic
https://www.dropbox.com/s/b5epme2llgq87ei/iconInfo.svg

**Comment by chloeatplay** [comment]
Hey @zzzndr can you quickly explain how it works and provide a quick visual? The wiki page has a ton of things on it ;)

**Comment by zzzndr** [comment]
aah of course (:
here is a cutout of the relevant part (:

info

the idea is to put the [ i ] icon in the top left of the badge container, the corresponding badge page is loaded when clicked (:

**Comment by stenington** [comment]
@chloeatplay @zzzndr This conflicts with what I had in my head for the pathway progress indicator #260, which I was imagining as a checkbox where the `i` icon is. I could do it as a checkbox in the upper right as shown above, though that would overlap the core badge icon on core badges. Maybe that's okay?

**Comment by chloeatplay** [comment]
Yeah, that was my initial question to @zzzndr when he showed this. I would say that maybe for the progress indicator it is ok to overlap? not sure- ....

**Comment by zzzndr** [comment]
I would make the badge title underlined & clickable!
If that solution isn't obvious enough perhaps we can add in text [ i ]  after the last character of the text?

if you want i can quickly create a mockup?

**Pull request merged**
